[versions]
kotlin = "1.8.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
