# コミットごとに Unit Test 実行
name: Build & Test

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - name: Build
        run: |
          ./gradlew :library:testClasses
      - name: Test
        run: |
          ./gradlew :library:test
      - uses: EnricoMi/publish-unit-test-result-action/linux@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          junit_files: "**/build/test-results/*/*.xml"
          comment_mode: off
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: "**/build/reports/tests/*"
